image: hseeberger/scala-sbt:11.0.6_1.3.10_2.13.1

stages:
  - test

before_script:
  - sbt sbtVersion
  - sbt update

# run tests separately due to memory restrictions (4GB for shared runner of gitlab)
# insert new testOnly commands if new test-packages are inserted
test:
  stage: test
  script:
    - sbt compile
    - sbt "testOnly inca.runtime.**"
    - sbt "testOnly inca.backend.**"
    - sbt "testOnly inca.debugger.**"
    - sbt "testOnly inca.frontend.functional.**"
    - sbt "testOnly inca.frontend.constraint.**"
    - sbt "testOnly inca.caseStudies.**"
