image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1

stages:
  - test

before_script:
  - apt-get update -qq
  - apt-cache madison z3
  - apt-cache policy z3
  - apt-get -y install z3=4.8.17
  - sbt sbtVersion
  - sbt update

test:
  stage: test
  script:
    - sbt clean test
