// expressions
edb num(Any, Int).
edb add(Any, Any, Any). // expression + expression
edb var(Any, String). // var read
// statements
edb vardef(Any, String, Any). // stmt, name, expr
edb next(Any, Any). // stmt1; stmt2
edb first(Any). // the first statement of a program

cflow(Any, Any).
cflow(s1, s2) :- vardef(s1, n, e), next(s1, s2).

//
ceval(Any, Any, Int). // statement, expression, value
// stmt := ..., expr is a number
ceval(stmt, expr, value) :- vardef(stmt, _, e), num(expr, value).
// stmt := v = _expr, expr := var(v),
ceval(stmt, expr, value) :- vardef(stmt, name, e), var(expr, v), nextIDB(stmt1, stmt), name == v, ceval(stmt1, e, value1), value == value1.
                                                                                                                                    ceval(stmt, expr, value) :- vardef(stmt, name, e), var(expr, v), nextIDB(stmt1, stmt), name != v, ceval(stmt1, expr, value1), value == value1.
                                                                                                                                                                                                                                                                           ceval(stmt2, expr, value) :- vardef(stmt2, _, expr), add(expr, lhs, rhs), nextIDB(stmt1, stmt2), ceval(stmt1, lhs, res1), ceval(stmt1, rhs, res2), value == res1 + res2.

                                                                                                                                                                                                                                                                                                                                                                                                                                              nextIDB(Any, Any).
nextIDB(stmt1, stmt2) :- next(stmt1, stmt2).
nextIDB(stmt1, stmt1) :- first(stmt1).
//
cvalue(Any, String, Int).
cvalue(s2, name, value) :- nextIDB(s1, s2), vardef(s2, name, expr), ceval(s2, expr, value).
