// a = 5        // a == 5
// b = 6        // a == 5, b == 6

// expressions
edb num(Any, Int).
edb add(Any, Any, Any). // expression + expression
edb var(Any, String). // var read

// statements
edb vardef(Any, String, Any). // stmt, name, expr
edb next(Any, Any).

// cvalue(Any, String, Int).

ceval(Any, Int).
ceval(expr, value) :- num(expr, value).
ceval(expr, value) :- add(expr, lhs, rhs), ceval(lhs, r1), ceval(rhs, r2), value == r1 + r2.
                                                                                         ceval(expr, value) :- var(expr, name), vardef(stmt, name, initexpr), ceval(initexpr, value).

cvalue(Any, String, Int).
cvalue(s1, name, value) :- vardef(s1, name, expr), ceval(expr, value).
cvalue(s2, name, value) :- next(s1, s2), cvalue(s1, name, value). // vardef(s2, n, e),
