.decl zero(x: number)

.comp Component {
    .decl edge(x: symbol, y: symbol)
    edge("a", "b").
    edge("b", "c").
    edge("c", "b").
    edge("c", "d").

    .comp InnerComponent {
        .decl path(x: symbol, y: symbol)
        path(x, y) :- edge(x, y).
        path(x, y) :- edge(x, z), path(z, y).
        zero(5).
    }

    .comp InnerComponent2 {
        .decl path(x: symbol, y: symbol)
        path(x, y) :- edge(x, y).
        path(x, y) :- path(x, z), edge(z, y).
        zero(4).
    }

    .init innerComp = InnerComponent
    .init innerComp2 = InnerComponent2
}

.init comp = Component
/*
// Not obvious how to handle / compile this
comp.edge("a", "b").
comp.edge("b", "c").
comp.edge("c", "b").
comp.edge("c", "d").
*/
.output comp.innerComp.path
.output comp.innerComp2.path
.output zero